openapi: 3.0.0
info:
  title: Funds
  version: '1.0'
  contact:
    name: nat
    email: nat.christanto@email.ottodigital.id
  description: 'API to conduct transaction using a source of funds  '
servers:
  - url: 'https://funds.ottodigital.id'
    description: funds
paths:
  /payments:
    post:
      summary: Payment
      operationId: post-transactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment-response'
              examples:
                payment-success:
                  value:
                    response_code: G0000
                    response_message: SUCCESS
                    meta:
                      debug_param: ''
                    mobile_phone_number: '085780873248'
                    trace_id: blr-231-890
                    product_details:
                      product_code: SIMANIS
                      product_name: Pembelian Emas
                      billing_group: INVESTMENT
                    references:
                      app_reference_number: PEDE-89011234
                      app_code: PEDE
                      user_api_key: cd78h1loenuxmq
                      sof_id: 231
                      sof_reference_number: B789kuolpsw3
                    money:
                      amount: 8000
                      fee: 0
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
              examples:
                error-sample:
                  value:
                    mobile_phone_number: '08129489292'
                    response_code: G0001
                    response_message: Internal error occured
                    meta:
                      debug_param: HMAC verification failed
                    trace_id: 8B45E57B2D28BC4C238BEC01BCC68796
      description: create a payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment-request'
            examples:
              payment-req-sample:
                value:
                  mobile_phone_number: '085780873248'
                  trace_id: blr-231-890
                  product_details:
                    product_code: SIMANIS
                    product_name: Pembelian Emas
                    billing_group: INVESTMENT
                  references:
                    app_reference_number: PEDE-89011234
                    app_code: PEDE
                    user_api_key: cd78h1loenuxmq
                  money:
                    amount: 8000
                    fee: 0
                  credentials:
                    password:
                      key_version: 2
                      value: 0bGKqoTexw7QAt0OpuCHHMwMpadqKuSCDaOhjiGkL7cdxCxROlQR2yfg3YDz44MeqwP8fe+l45GvGvDyjE7g5LVQMAxDyaA+2HENSlKkEExS+uHfjYcxjbCBlwEbMPf9zS3cKYHA2PbHNxpa8Aubr9KkBENxORqB2zzw0e0HmSMHJu1kcWA9M1AIFIpPSiCTJuCmg3E4KNzShFlP5LbBiOWtQhHts4G7geSgUtgWuv4=
                      format: aes-cbc
          application/xml:
            schema:
              type: object
              properties: {}
        description: A payment request
      security:
        - client-grant: []
      tags:
        - transactions
    parameters: []
components:
  schemas:
    payment-request:
      title: payment-request
      type: object
      x-examples:
        sample-payment-request:
          account_no: '085780873248'
          trace_id: blr-231-890
          product_details:
            product_code: SIMANIS
            product_name: Pembelian Emas
            billing_group: INVESTMENT
          references:
            app_reference_number: PEDE-89011234
            app_code: PEDE
            user_api_key: cd78h1loenuxmq
          money:
            amount: 8000
            fee: 0
          credentials:
            password:
              key_version: 2
              value: 0bGKqoTexw7QAt0OpuCHHMwMpadqKuSCDaOhjiGkL7cdxCxROlQR2yfg3YDz44MeqwP8fe+l45GvGvDyjE7g5LVQMAxDyaA+2HENSlKkEExS+uHfjYcxjbCBlwEbMPf9zS3cKYHA2PbHNxpa8Aubr9KkBENxORqB2zzw0e0HmSMHJu1kcWA9M1AIFIpPSiCTJuCmg3E4KNzShFlP5LbBiOWtQhHts4G7geSgUtgWuv4=
              format: aes-cbc
      description: a payment request model
      properties:
        account_no:
          type: string
        trace_id:
          type: string
        product_details:
          type: object
          required:
            - product_name
            - billing_group
            - product_code
          properties:
            product_name:
              type: string
            billing_group:
              type: string
            product_code:
              type: string
        references:
          type: object
          required:
            - app_reference_number
            - app_code
          properties:
            app_reference_number:
              type: string
            app_code:
              type: string
            user_api_key:
              type: string
        credentials:
          type: object
          properties:
            password:
              type: object
              properties:
                key_version:
                  type: string
                format:
                  type: string
                value:
                  type: string
        money:
          type: object
          properties:
            amount:
              type: integer
            fee:
              type: integer
      required:
        - account_no
        - trace_id
        - product_details
        - references
    payment-response:
      title: payment-response
      type: object
      description: a response after successfully capturing a payment
      x-examples:
        'payment success ':
          response_code: G0000
          response_message: SUCCESS
          meta:
            debug_param: ''
          account_no: '085780873248'
          trace_id: blr-231-890
          product_details:
            product_code: SIMANIS
            product_name: Pembelian Emas
            billing_group: INVESTMENT
          references:
            app_reference_number: PEDE-89011234
            app_code: PEDE
            user_api_key: cd78h1loenuxmq
            sof_id: 231
            sof_reference_number: B789kuolpsw3
          money:
            amount: 8000
            fee: 0
      properties:
        response_code:
          type: string
        response_message:
          type: string
        meta:
          $ref: '#/components/schemas/meta'
        trace_id:
          type: string
        account_no:
          type: string
        product_details:
          type: object
          properties:
            product_code:
              type: string
            product_name:
              type: string
            billing_group:
              type: string
        money:
          type: object
          properties:
            amount:
              type: integer
            fee:
              type: integer
        references:
          type: object
          properties:
            app_reference_number:
              type: string
            app_code:
              type: string
            sof_id:
              type: integer
            sof_reference_number:
              type: string
            user_api_key:
              type: string
    meta:
      title: meta
      type: object
      description: 'Meta struct for additional details. Might be used for troubleshooting, etc'
      properties:
        debug_param:
          type: string
    error-response:
      title: error-response
      type: object
      description: a general error response
      x-examples:
        error-sample:
          account_no: '08129489292'
          response_code: G0001
          response_message: Internal error occured
          meta:
            debug_param: HMAC verification failed
          trace_id: 8B45E57B2D28BC4C238BEC01BCC68796
      properties:
        account_no:
          type: string
        response_code:
          type: string
        response_message:
          type: string
        trace_id:
          type: string
        meta:
          $ref: '#/components/schemas/meta'
  securitySchemes:
    client-grant:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://token.ottodigital.id'
          scopes:
            read: read a resource
            write: write a resource
          refreshUrl: 'https://refresh.ottodigital.id'
      description: a grant access that will be used by partner
tags:
  - name: transactions
